### ISSUE TITLE
Windows tar JRE version error

### ISSUE THREAD

**Issue by Kimrli** [janhubicka/Color-Screen#3]
I tried the win binary package and it seems we have different JRE versions:
```
PS L:\Documents\Color-Screen\Color-Screen-GUI\target> java -jar .\color-screen-gui-1.0-SNAPSHOT-jar-with-dependencies.jar
čvc 10, 2024 11:38:21 DOP. com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @75e9e93a'
C:\Program Files\Java\jdk-21\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCL
S Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\Phys
X\Common;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engin
e Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v
1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;L:\Aplikace\swipl\bin;C:\Program Files\dotnet\;L:\Aplikace\TortoiseSVN\bin;L:\Aplikace\Git\cmd;C:\Users\linda\.cargo\bin;C:\Users\linda\AppD
ata\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\ghcup\bin;C:\Users\linda\.dotnet\tools;C:\Users\linda\AppData\Local\GitHubDesktop\bin;L:\Program Files\Jet Brains\PyCharm Community Edition 2023.3.2\bin;;L:\Aplikace\JetBrains\IntelliJ IDEA Community Edition 2024.1.1\bin;;L:\Aplikace\msys64\mingw64\bin;L:\Aplikace\msys64\mingw32\bin;;.
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class cz.cuni.mff.java.digitalColoring.GUI.ColorScreenGUI
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:883)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.UnsatisfiedLinkError: L:\Documents\Color-Screen\Color-Screen-GUI\target\render.dll: Uvedená procedura nebyla nalezena
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:259)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:251)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2451)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
        at java.base/java.lang.System.loadLibrary(System.java:2063)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:795)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
        ... 1 more
PS L:\Documents\Color-Screen\Color-Screen-GUI\target> java -jar .\color-screen-gui-1.0-SNAPSHOT-jar-with-dependencies.jar
čvc 10, 2024 11:47:17 DOP. com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @75e9e93a'
C:\Program Files\Java\jdk-21\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCL
S Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\Phys
X\Common;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engin
e Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v
1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;L:\Aplikace\swipl\bin;C:\Program Files\dotnet\;L:\Aplikace\TortoiseSVN\bin;L:\Aplikace\Git\cmd;C:\Users\linda\.cargo\bin;C:\Users\linda\AppD
ata\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\ghcup\bin;C:\Users\linda\.dotnet\tools;C:\Users\linda\AppData\Local\GitHubDesktop\bin;L:\Program Files\Jet Brains\PyCharm Community Edition 2023.3.2\bin;;L:\Aplikace\JetBrains\IntelliJ IDEA Community Edition 2024.1.1\bin;;L:\Aplikace\msys64\mingw64\bin;L:\Aplikace\msys64\mingw32\bin;;.
11:47:18.504567800 INFO: (STATUS-BAR) Panel initialization started.
11:47:18.544437600 INFO: (TOOL-BAR) Tool bar initialization started.
Exception in Application constructor
Exception in thread "main" java.lang.RuntimeException: Unable to construct Application instance: class cz.cuni.mff.java.digitalColoring.GUI.ColorScreenGUI
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:883)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:74)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:795)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:483)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:456)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:455)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:185)
        ... 1 more
Caused by: java.lang.UnsupportedClassVersionError: cz/cuni/mff/java/digitalColoring/interfaceWithC/Render$RenderType has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 65.0
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at cz.cuni.mff.java.digitalColoring.GUI.RenderBar.<init>(RenderBar.java:18)
        at cz.cuni.mff.java.digitalColoring.GUI.ColorScreenGUI.<init>(ColorScreenGUI.java:77)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
        ... 11 more
```

**Comment by Kimrli** [comment]
My java version is:
```
java version "21.0.3" 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)
```

**Comment by janhubicka** [comment]
Sorry did not notice this. The yml file lets me to  choose version so I will try to downgrade it.

**Comment by janhubicka** [comment]
I downgraded Java to 18 for build and it works on my Windows setup with windows 19.
That strange error message actually seems to be caused by fact that I forgot to package libcolorscreen
